// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmieugwgcgmnrphpopru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtaWV1Z3dnY2dtbnJwaHBvcHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODQzNzYsImV4cCI6MjA3MTQ2MDM3Nn0.EAUEKVb8-NmMueZwXp9NKD9RKnQ44ImHXWA6JelSm2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});